on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Every Sunday @ 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: ./.github/scripts/build.sh
        env:
          REPO: perfectknot/php-laravel
