name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and publish
        run: ./.github/scripts/build.sh
        env:
          REPO: perfectknot/php-laravel
